version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=******** # change it!
      - POSTGRES_DB=postgres
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: sh -c "service redis-server start && python /var/www/lister/lister/manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/var/www/lister
    ports:
      - "80:80"
    depends_on:
      - db
