# Generated by Django 3.0 on 2020-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='author',
            new_name='item_author',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_date',
            new_name='item_created',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='exec_date',
            new_name='item_executed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='typeof',
        ),
        migrations.AddField(
            model_name='item',
            name='item_counttype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_isdone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
