# Generated by Django 3.0 on 2020-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_auto_20200319_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_count',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_counttype',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
