# Generated by Django 3.0 on 2020-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0004_auto_20200321_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_counttype',
            field=models.CharField(choices=[('l', 'l'), ('kg', 'kg'), ('pc', 'pc')], max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_isdone',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=False, max_length=5),
        ),
    ]
