# Generated by Django 3.0 on 2020-03-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0006_auto_20200321_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('food and drink', 'food and drink'), ('household products', 'household products'), ('books and stationery', 'books and stationery'), ('electronics and devices', 'electronics and devices'), ('health and medicine', 'health and medicine'), ('education', 'education'), ('repair', 'repair'), ('cosmetics and beauty', 'cosmetics and beauty'), ('clothes and shoes', 'clothes and shoes'), ('art and music', 'art and music'), ('services', 'services'), ('other', 'other')], max_length=50),
        ),
    ]
