# Generated by Django 3.0 on 2020-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0010_auto_20200601_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
