# Generated by Django 3.0 on 2020-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0011_code_code_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_step',
            field=models.IntegerField(default=0),
        ),
    ]
