# Generated by Django 3.0 on 2021-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0014_auto_20210727_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_token',
            field=models.CharField(default=None, max_length=130),
        ),
    ]
